declare module '*.png';
declare module '*.svg';
declare module '*.jpg';
declare module '*.gif';
declare module 'reactjs-localstorage';
declare module 'react-fullscreen-loading';
declare module 'country-list-json';
// declare module 'react-copy-to-clipboard';
// declare module 'file-saver';
// declare module 'react-bootstrap-image-cropper';
